(function() {var implementors = {};
implementors["odds"] = ["impl&lt;'a, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;&amp;'a [T]&gt; for <a class=\"struct\" href=\"odds/slice/iter/struct.SliceCopyIter.html\" title=\"struct odds::slice::iter::SliceCopyIter\">SliceCopyIter</a>&lt;'a, T&gt; <span class=\"where fmt-newline\">where T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a></span>","impl&lt;'a, T, Slice:&nbsp;?<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;&amp;'a Slice&gt; for &amp;'a <a class=\"struct\" href=\"odds/slice/struct.RevSlice.html\" title=\"struct odds::slice::RevSlice\">RevSlice</a>&lt;T&gt; <span class=\"where fmt-newline\">where Slice: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;[T]&gt;</span>","impl&lt;'a, T, Slice:&nbsp;?<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;&amp;'a mut Slice&gt; for &amp;'a mut <a class=\"struct\" href=\"odds/slice/struct.RevSlice.html\" title=\"struct odds::slice::RevSlice\">RevSlice</a>&lt;T&gt; <span class=\"where fmt-newline\">where Slice: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsMut.html\" title=\"trait core::convert::AsMut\">AsMut</a>&lt;[T]&gt;</span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
